### ISSUE TITLE
[FEAT REQUEST] Add support for custom localized content within a Polaris

### ISSUE THREAD

**Issue by blanklob** [Shopify/shopify-app-template-remix#302]
It will be great if the template how or uses an example of localized content, that is setup and ready to use with Remix.

Currently thinking of using: https://github.com/sergiodxa/remix-i18next by @sergiodxa 

-- Other ressources --

Polaris i18n guide: https://polaris.shopify.com/components/utilities/app-provider#using-translations

**Comment by JannikWempe** [comment]
I am currently trying to add i18n to my Remix app. Without success so far (even with the reference implementations, maybe due to Remix v2?).

> But in the end we decided against including it by default because it adds complexity to every app, regardless of if it's needed. There are very valid cases where it is just not relevant.

I get that it does not necessarily make sense in this template (maybe as an option?). But do you now the reason for not including the functionality in `@shopify/shopify-app-remix`? That would certainly help having more localized apps.

**Comment by AxeemHaider** [comment]
@soft-blockk @pama1999 Did you find the solution?

**Comment by pama1999** [comment]
@AxeemHaider 
nope still lookign
