### ISSUE TITLE
How to use the GraphQL API in Remix's App separately from Shopify

### ISSUE THREAD

**Issue by Yamashou** [Shopify/shopify-app-template-remix#335]
# Issue summary

It can be seen from the sample that we hit the Shopify API from Remix's App. I would like to use another GraphQL API in addition to this. I can just call it, but if I want to generate a type such as GraphQL Code Generator, Qeury conflicts with it and I can't generate it. Is there any way to resolve this?

my graphql code generator config
```
const config: CodegenConfig = {
  overwrite: true,
  ignoreNoDocuments: true,
  generates: {
    "app/shopify/": {
      preset: "client",
      documents: ["app/**/*.tsx"],
      schema: "https://shopify.dev/admin-graphql-direct-proxy/2023-07",
      presetConfig: {},
      documentTransforms: [],
      plugins: []
    },
    "app/erp/": {
      preset: "client",
      documents: ["app/**/*.tsx"],
      schema: "https://my-api-url/graphql",
      presetConfig: {},
      documentTransforms: [],
      plugins: []
    }
  }
};
```

- `@shopify/shopify-app-remix` version: 1.0.3
- Node version: v18.17.1
- Operating system: macOS

```
// Paste any relevant logs here
```

## Steps to reproduce the problem

1.
1.
1.

**Comment by byrichardpowell** [comment]
Hey @Yamashou 

We can't really help you with this issue because we don't support `graphql code generator` in the template by default and it's not a tool I know a great deal about.  But! I think you could consider opening an issue with the maintainer of `graphql code generator` and hopefully they can help you.

I'm going to close this issue for now.  But if this is ever something we support we'll try to consider this use case.

Thanks for choosing to build on the Shopify platform and good luck with your app.

Richard
