### ISSUE TITLE
Error: Migration engine exited

### ISSUE THREAD

**Issue by mumarse** [Shopify/shopify-app-template-remix#337]
why i am facing this error, my node modules is up-to-date, internet connection is good. when i 'npm run dev' command server starts then this error occurs and server closed/crashes,

import { PrismaClient } from '@prisma/client'const prisma = new PrismaClient()
```
Prisma schema loaded from prisma\schema.prisma
Datasource "db": SQLite database "dev.sqlite" at "file:dev.sqlite"

Error: Migration engine exited. Error: Command failed with exit code 3221225477: C:\Users\Hamza Khan\Desktop\Digiware2\New folder\stable-duplication-app\node_modules\@prisma\engines\migration-engine-windows.exe cli --datasource <REDACTED> can-connect-to-database

**Comment by paulomarg** [comment]
Hi, this seems to be a bug in Prisma itself, and not our package, so unfortunately there's not much we can do about it from here. We're just calling the Prisma migration command from the template.

Based on the error message, it sounds like:
- you may not have permissions to write to your DB path
- the `C:\Users\Hamza Khan\Desktop\...` bit of your path may be an issue because of the space. You could try using a different folder path without spaces in it to see if it help.

I'm going to close this issue since we can't really solve it from this package, but I hope this helps!
