### ISSUE TITLE
Async fetch requests to the server

### ISSUE THREAD

**Issue by mashkovtsevlx** [Shopify/shopify-app-template-remix#348]
# Issue summary
In the examples provided by Shopify and Remix - App uses useSubmit and useFetcher hooks to send requests to a server. 
Both these hooks allow only one request to be sent at a time. 
Is there any way we can use native fetch to send authenticated requests to a server simultaneously?

- `@shopify/shopify-app-remix` version: 1.1.0
- Node version: 18
- Operating system: MacOS

## Expected behavior

Multiple fetch requests being sent at a same time are getting processed asynchronously.

## Actual behavior

When using useSubmit and useFetcher - the previous request gets canceled if the new request was sent using the same useSubmit instance.

**Comment by byrichardpowell** [comment]
Hey @mashkovtsevlx 

Can you use `useFetcher`? [Here is a commit](https://github.com/Shopify/shopify-app-template-remix/commit/c41f3e37533838c4fda6d10c3ea708c313637102) where I took the generate product example and added a second button.

Here's a video of it in action:

https://github.com/Shopify/shopify-app-template-remix/assets/690791/d5b27403-595c-4864-9479-23e0ce6295f3

To explain this, first we use `useFetcher` twice:

```ts
const fetcher1 = useFetcher();
const fetcher2 = useFetcher();
```

Each generate product button will call it's own fetcher:

```ts
const generateProduct = () => fetcher1.submit({}, { replace: true, method: "POST" });
const generateProduct2 = () => fetcher2.submit({}, { replace: true, method: "POST" });
```

Which allows each button to manage it's own loading state:

```ts
<Button
  loading={fetcher1.state !== "idle"}
  primary
  onClick={generateProduct}
>
  Generate a product (1)
</Button>
<Button
  loading={fetcher2.state !== "idle"}
  primary
  onClick={generateProduct2}
>
  Generate a product (2)
</Button>
```

Both `useSubmit` and `useFetcher` use `window.fetch` under hood.  In the background App Bridge patches `window.fetch` to always include the authorization header.

Since, I think this answers your question I'm going to close this issue.

Good luck with your app and thanks for building on top of Shopify!
