### ISSUE TITLE
Get admin object from authenticate.public(request)

### ISSUE THREAD

**Issue by LHongy** [Shopify/shopify-app-template-remix#349]
Hi, I am creating an API for my checkout extension, I use this code to authenticate the request: 
`const { cors, sessionToken } = await authenticate.public(request);`

In my usecase, I need to first query data from Shopify admin, process some logic, then response custom data to the checkout extension. Is there a way to get the admin object in authenticate.public like what we can in authenticate.admin:
`const { admin, session } = await authenticate.admin(request);`?

**Comment by paulomarg** [comment]
Thanks for your question.

We don't return the `admin` context from `authenticate.public` (soon to be `authenticate.public.checkout`), but you can use the information in `sessionToken` to create an [unauthenticated admin context](https://shopify.dev/docs/api/shopify-app-remix/v1/unauthenticated/unauthenticated-admin), since the request is already authenticated by that point.

Since this isn't a bug in the package, I'll close the issue, but please let us know if you run into any problems.
