### ISSUE TITLE
Webhooks not registering 

### ISSUE THREAD

**Issue by nboliver-ventureweb** [Shopify/shopify-app-template-remix#420]
# Issue summary

With a fresh Remix app template, I added a new webhook in shopify.server.js 
```
   DRAFT_ORDERS_CREATE: {
      deliveryMethod: DeliveryMethod.Http,
      callbackUrl: "/webhooks",
   },
```

In routes/webhooks.jsx, I added a new case for the webhook: 
```
    case "DRAFT_ORDERS_CREATE":
      console.log(payload);
      break;
```

Running `npm run dev` and testing with the CLI `shopify webhook trigger` gives a 200 response but testing with an action in the dev store (ie. creating a draft order) does nothing.

- `@shopify/shopify-app-remix` version: 2.1.0
- Node version: 18.16.0
- Operating system: MacOS

CLI webhook trigger test:
```
20:33:22 │ remix │ [shopify-api/DEBUG] Webhook request is well formed | 
{apiVersion: 2023-10, domain: shop.myshopify.com, topic: DRAFT_ORDERS_CREATE, 
webhookId: 8248c491-6643-4c8c-a53e-eec06328bc0b}
20:33:22 │ remix │ [shopify-api/DEBUG] Webhook request is valid | {apiVersion:
 2023-10, domain: shop.myshopify.com, topic: DRAFT_ORDERS_CREATE, webhookId: 
8248c491-6643-4c8c-a53e-eec06328bc0b}
```

## Expected behavior

Webhook callback should run / `admin` shouldn't be undefined 

## Actual behavior

Nothing happens

## Steps to reproduce the problem

1. Create a new app and add a webhook as described above
2. Run `npm run dev`
3. Go to the store and initiate an action that should trigger the webhook
4. nothing happens

**Comment by nboliver-ventureweb** [comment]
Update: when using the `npm run dev -- --reset` command, and choosing to use an existing app, any scopes that were updated locally are overwritten. This meant that hooks were not being registered. Is this expected behaviour? I had to create a new app in the partners account in order to update the scopes. Is this expected?

**Comment by paulomarg** [comment]
Hi, thank you for your report! Currently, webhooks are registered after the app performs OAuth, which happens when the app is installed or a new API access token needs to be generated.

The easiest way to update your webhook subscriptions during development is to uninstall your app and reinstall it, so that it authenticates again. We should be more explicit about this in our troubleshooting section, we'll add that issue to the list.

As for changing the scopes, running `config link` and `config push` will probably help: https://github.com/Shopify/shopify-app-template-remix#oauth-goes-into-a-loop-when-i-change-my-apps-scopes

**Comment by nboliver-ventureweb** [comment]
Thanks @paulomarg - both those tips are helpful.
