### ISSUE TITLE
No "Console.logs()" are output

### ISSUE THREAD

**Issue by Ellopix** [Shopify/shopify-app-template-remix#608]
# Issue summary

Before opening this issue, I have:

- [x] Upgraded to the latest version of the `@shopify` packages
  - Affected `@shopify/shopify-*` package and version:
     "@remix-run/dev": "^2.7.1",
    "@remix-run/node": "^2.7.1",
    "@remix-run/react": "^2.7.1",
    "@remix-run/serve": "^2.7.1",
    "@shopify/app": "3.57.0",
    "@shopify/cli": "3.57.0",
    "@shopify/polaris": "^12.0.0",
    "@shopify/shopify-api": "^9.2.0",
    "@shopify/shopify-app-remix": "^2.5.0",
  - Node version: v18.12.0
  - Operating system: MacOS 14.0 
- [x] Set `{ logger: { level: LogSeverity.Debug } }` in my configuration
- [ ] Found a reliable way to reproduce the problem that indicates it's a problem with the package
- [x] Looked for similar issues in this repository
- [x] Checked that this isn't an issue with a Shopify API

## Description
No matter where I place my own _Console.log()_, no logs are output. I have also set the logger to debug. 
The project is an empty template and is started locally with _npm run dev_

## Expected behavior

What do you think should happen?

Print logs.

## Actual behavior

What actually happens?

Nothing.

## Debug logs

**Comment by lizkenyon** [comment]
Hi there 👋 

Your console.logs should be working. If they are not working could you please provide us with your example repository for us to replicate. 

If you have your console.logs in your loader functions, then you will expect the output to be in your terminal server logs. Because this code is run on the server.



![Image](https://github.com/Shopify/shopify-app-template-remix/assets/23265671/b05934cf-6a42-4981-b570-ed89aa5e9f21)



![Image](https://github.com/Shopify/shopify-app-template-remix/assets/23265671/d6b9e4ed-1cb7-437f-9ac6-2ecce9a9e4e7)



![Image](https://github.com/Shopify/shopify-app-template-remix/assets/23265671/dbf755e3-5751-4a74-89f7-ea00b5ade33d)
