### ISSUE TITLE
No AppBridge context provided

### ISSUE THREAD

**Issue by NijatBakhtiyar** [Shopify/shopify-app-template-remix#618]
# Issue summary

I have upgraded app-bridge-react version to latest(v4) to use some new components(Modal etc.). But I have met a issue about provider

<img width="514" alt="Screen Shot 2024-03-19 at 12 16 54 AM" src="https://github.com/Shopify/shopify-app-template-remix/assets/76853621/a8e45274-8d09-4273-9f58-f73f4c6d241d">

When I use new components "TitleBar" or "Modal" this issue happens. I have added app-bridge.js and clinet_id to meta tag. I've made all as migration file. Everything is okay when I don't import or use new components.

<img width="455" alt="image" src="https://github.com/Shopify/shopify-app-template-remix/assets/76853621/f800336b-f1fb-464c-adfc-1baa36bce30a">

**Comment by hamzasgd** [comment]
@NijatBakhtiyar, I suggest removing the @shopify/app-bridge:3.7.0 and instead using the latest CDN version of App Bridge that doesn't require any context provider. Also, since your App Bridge React version is 4.1.1, you should definitely use the latest @shopify/app-bridge version that matches your App Bridge React version. check this link [https://shopify.dev/docs/api/app-bridge-library](url)
