### ISSUE TITLE
Shopify Remix Billing API - Issues with Test Mode

### ISSUE THREAD

**Issue by polymorphtech** [Shopify/shopify-app-template-remix#708]
I'm stuck in the final stages of app approval due to challenges with the Remix Billing API.

- When I test my my app on my development store, I am able to successfully initiate real, non-test charges (initiate, but not complete, because development stores cannot process real charges). 
- However, when the app store review team tests my app on a non-development store, they tell me they experience only test charges ([Screencast](https://mail.shopifysvc.com/_t/c/A102004F-17C98FDE90AFD0D9-92B8D69D?l=AADO25OS%2FUBHB%2BQJvMRXRh21RtpCr6n4jJPt%2B7uuwXALnlOtYm0R3%2BkLbkMYWGtuuuiUOQJx9xJniA1QQHmr%2BTVi1Gest%2BXjNkdNSJrHppKDTyhx6y13tDz05q9Cmb2ReClbfpaaXHS8If23UABFNn3IgLuALSuHTD2WdT3eCMB8DnbSDWHt73p079Ba&c=AAAvUbWv%2FESF42cVsc%2Fjb%2FKJcsgw6Ox8lRJQ9oYyTX9KQ8oWQ12Q3DwCdgsBA1Zmxrnvnd%2Bo4xKGyZsSk62QJIolLK0zgRlFsxAcDtMDKq3NY13zaCfNLKKRHRIG7W%2BnRMWrmqqVNan8Ba7QdyQu9KFzbTn3qe6NLxbKhFp59fSkpeb4c8S%2Fq%2BrjQgU9w8qRVQh69rnilY%2FXqCbTb1WFu3NPcQajoiW05087Zy1c%2Fhm%2FbaX0V8aEKeSQ4CxJBOSkLVT6PyHvvR5HuV8JUqvU3ks%2FvY0x7pbEPU8CdftoFSe%2F%2F3zBfTuaV%2FGiv4C0EQYRArcobAS6aUh3OpeTGlDd3Xe4lhlVgQ%3D%3D))
- Since developers cannot test apps on non-development stores, the app store team tried to give me staff access to a non-development store so I could replicate the issue they're seeing. But that didn't work as the staff access still had permissions issues and did not allow me to access the page to approve charges ([Screenshot](https://drive.google.com/file/d/1ulnRy9AsMPjXqrwzqVz8w8c7CGhvSBqf/view?usp=sharing))

Here are all the calls I make to the Billing API:

> const billingTest = false;
> const { billing } = await authenticate.admin(request);

> const { hasActivePayment, appSubscriptions } = 
await billing.check({
    plans: [MONTHLY_PLAN],
    isTest: billingTest,
  });

> await billing.cancel({
        subscriptionId: appSubscriptions[0].id,
        isTest: billingTest,
        prorate: true,
      });

> await billing.require({
        plans: [MONTHLY_PLAN],
        isTest: billingTest,
        onFailure: async () => billing.request({ plan: MONTHLY_PLAN, isTest: billingTest, returnUrl: planPageUrl }),
      });`

[Here](https://stackblitz.com/~/github.com/polymorphtech/remix-billiing-plan) is a stackblitz for the "Plan" page.

Appreciate guidance from the dev team

## Expected behavior

Real non-test charges should be initiated on all stores: development & non-development stores

## Actual behavior

Real non-test charges are being initiated on development stores. Questionable behaviour occurring on non-development stores

**Comment by lizkenyon** [comment]
Hi there 👋 

I believe what is happening here is actually this:

The App reviewer is testing your app on a Staff Plan store. This store can only create test charges not real charges.
Even though you have set `isTest` to false, a test charge is created.

Your billing.check method checks to see if a non test charge has been created, which none have. (A test charge was created.) 
Because a real charge was not created, your application sends them back to billing plan page.

We are looking to [add a feature](https://github.com/Shopify/shopify-app-js/issues/574) in the future, to detect if a shop is a Staff store so that we can provide this information to the billing.check method to default the isTest to true in those scenarios.

In the meantime you may need to set `isTest` to true while your app is being reviewed. 

If this is not the issue, and you are being told that you should be creating real charges in the App Review process you may want to reach out to partner support for clarification.

**Comment by polymorphtech** [comment]
Thanks for the swift response, Liz. 

-  I had a feeling staff stores had some different behaviour going on, thank you for confirming that is the case
- To confirm, you're suggesting to make isTest true for just the billing.check method call, correct?
- And this is because staff stores override the isTest flag to make them true on billing method calls

**Comment by maneko00** [comment]
Thank you for your reply.

I could not find the Staff store from the Shop object.
Could you please tell me how to find it?
