### ISSUE TITLE
Migrate Sqlite database to PostgreSQL

### ISSUE THREAD

**Issue by aryankashyap7** [Shopify/shopify-app-template-remix#715]
I wanna migrate my SQLite database to PostgreSQL. What would be the procedure?

**Comment by matteodepalo** [comment]
Hi @aryankashyap7, this repo is for issues related to the remix template. May I recommend you open a new discussion on the [tools board](https://community.shopify.com/c/shopify-cli-and-tools/bd-p/tools)? Thank you.

**Comment by jeffreygnatek** [comment]
i wanted to comment here in case anyone finds this searching,

when you follow the directions to move to postgres, you might encounter errors because DateTime is not in Postgres.

I spent hours chasing this and the solution is that you need to manually modify the existing initial migration created when you set up your Remix app. You need to change expires to "expires" TIMESTAMP(3), which is supported by Postgres. Hope that saves someone time in the future.
