### ISSUE TITLE
How to persist Shopify app session after Google oAuth2 in Embed app

### ISSUE THREAD

**Issue by michaelhunter555** [Shopify/shopify-app-template-remix#832]
I'm converting a Google ads app to a shopify embedded app, but I'm having issues with persisting the session

`Question:` How can I maintain the current active session in Shopify for a user after they have successfully authorized the app via Google oAuth2?

`Intended functionality:` After successfully completing Google oAuth2 flow, users should be brought back to the app with their session (prior to Google oAuth2) maintained.

`Current functionality:` I am redirected to the auth.login page, presumably because my session is lost. my auth/callback.tsx is never reached, and I don't receive the access & refresh tokens.

Initially, I tried to do this with `redirect` from authenticate.admin and it maintained the session in embed, but this doesn't work (accounts.google.com doesn't allow for this).

 I am using the` application_url` in `shopify.app.toml`, specifically the 
`[auth] redirect_urls = [www.appname.trycloudflare.com/auth/callback]` 

Here's how it's working so far:
1. Check if user has google access_token & refresh_token on db
2. If no tokens, prompt them to authenticate with google
2.1. If access token, check validity, refresh if necessary & update db (finished)*
3.  Complete authorizing the app via Google oAuth2 then redirect to auth/callback.tsx
3.1. redirects to app login page... unintended*
------------------Login (enter your storename)------------------step 4 not completed*
4. Exchange code for access & refresh token, encrypt them, store on db (finished)*

After I authorize the Google Ads permissions, I want to return the user to the `auth.callback.tsx` route to exchange the code in the url response for access & refresh tokens. This is where I'm currently stuck because I'm being directed to the auth.login instead where im prompted to re-enter my dev_store_url.

**Comment by paulomarg** [comment]
Hey, thanks for raising this. I'm not sure how much we'll be able to help since it involves an external login, but I can think of a few things to keep in mind (I'm assuming you're going for an embedded app) - sorry if this is unrelated to your problem 😅:

<details>
<summary>Things that might be going wrong</summary>

1. Google's OAuth process is separate from Shopify's, so you'd need to go through both of them to get both sessions.
2. If you're using [managed installation](https://shopify.dev/docs/apps/build/authentication-authorization/app-installation) (the `unstable_newEmbeddedAuthStrategy` future flag is enabled), you won't have to do the redirects for Shopify's authentication.
   - The app will automatically generate / store a Shopify token when you call `authenticate.admin()`.
3. When working with embedded apps, you won't be able to use cookies to store sessions since they'd be considered 3rd party cookies, which browsers are making increasingly difficult to use.
4. The callback defined in the `shopify.app.toml` file only applies to Shopify's OAuth process, so you won't be able to call it from your app - that call is expected to come from Shopify.
</details>

All of that being said, based on your description, I'm guessing that in step 3 you shouldn't send the user to `auth/callback.tsx` after the Google OAuth, but instead you should send them to `https://<app-url>/?shop=<shop>` to avoid. The remix package will handle setting everything up as long as it knows what shop to load in.

I'd consider inverting things - in your routes, you could call

```ts
const {redirect, session} = authenticate.admin(request);

if (!googleToken) {
  // Go to google, and then have google redirect to `/?shop=<shop>`
  // I'm assuming they allow extra parameters
  throw redirect('<google-url>?shop=<session.shop>', { target: '_parent' });
}

// Have both tokens, app code goes here
```

For this type of question, we recommend going to the [Community Forums](https://community.shopify.com/c/partners-and-developers/ct-p/appdev) or Shopify Partner slack workspace, where other partners may have already gone through this same process.

Unfortunately, in this repo we only track bugs on our code, so there's not much more we can do here. If you do find a reproducible bug in the template / packages, please do report them!

Hope this helps!
